/**
 * API hata kodları (ADR-007). API metin değil kod döner; kullanıcıya gösterilen
 * mesaj web tarafında i18n ile üretilir (locales → errors.<KOD>).
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  CSRF_INVALID: 'CSRF_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SETUP_ALREADY_DONE: 'SETUP_ALREADY_DONE',
  SETUP_TOKEN_INVALID: 'SETUP_TOKEN_INVALID',

  ALREADY_MEMBER: 'ALREADY_MEMBER',
  INVITE_REQUIRES_LOGIN: 'INVITE_REQUIRES_LOGIN',
  INVITE_EMAIL_MISMATCH: 'INVITE_EMAIL_MISMATCH',
  LAST_OWNER: 'LAST_OWNER',
  OWNER_ONLY: 'OWNER_ONLY',

  SPACE_KEY_TAKEN: 'SPACE_KEY_TAKEN',
  GUEST_STAKEHOLDER_ONLY: 'GUEST_STAKEHOLDER_ONLY',
  GUEST_SPACES_REQUIRED: 'GUEST_SPACES_REQUIRED',
  CONTAINER_ARCHIVED: 'CONTAINER_ARCHIVED',

  WORK_ITEM_PARENT_REQUIRED: 'WORK_ITEM_PARENT_REQUIRED',
  WORK_ITEM_PARENT_NOT_ALLOWED: 'WORK_ITEM_PARENT_NOT_ALLOWED',
  WORK_ITEM_PARENT_SPACE: 'WORK_ITEM_PARENT_SPACE',
  WORK_ITEM_ESTIMATE_NOT_ALLOWED: 'WORK_ITEM_ESTIMATE_NOT_ALLOWED',
  WORK_ITEM_ESTIMATE_INVALID: 'WORK_ITEM_ESTIMATE_INVALID',
  WORK_ITEM_FIELD_NOT_ALLOWED: 'WORK_ITEM_FIELD_NOT_ALLOWED',
  WORK_ITEM_OPEN_CHILDREN: 'WORK_ITEM_OPEN_CHILDREN',
  WORK_ITEM_KEY_INVALID: 'WORK_ITEM_KEY_INVALID',
  WORK_ITEM_TYPE_NOT_ALLOWED: 'WORK_ITEM_TYPE_NOT_ALLOWED',
  LABEL_NAME_TAKEN: 'LABEL_NAME_TAKEN',
  WORK_ITEM_BLOCKED: 'WORK_ITEM_BLOCKED',
  WORK_ITEM_LINK_SELF: 'WORK_ITEM_LINK_SELF',
  WORK_ITEM_LINK_EXISTS: 'WORK_ITEM_LINK_EXISTS',
  WORK_ITEM_SPLIT_NOT_ALLOWED: 'WORK_ITEM_SPLIT_NOT_ALLOWED',
  CHECKLIST_LIMIT: 'CHECKLIST_LIMIT',
  COMMENT_FORBIDDEN: 'COMMENT_FORBIDDEN',
  REACTION_INVALID: 'REACTION_INVALID',
  ATTACHMENT_TOO_LARGE: 'ATTACHMENT_TOO_LARGE',
  ATTACHMENT_TYPE_BLOCKED: 'ATTACHMENT_TYPE_BLOCKED',
  ATTACHMENT_INVALID: 'ATTACHMENT_INVALID',
  ATTACHMENT_LIMIT: 'ATTACHMENT_LIMIT',
  AVATAR_INVALID: 'AVATAR_INVALID',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
