/**
 * API hata kodları (ADR-007). API metin değil kod döner; kullanıcıya gösterilen
 * mesaj web tarafında i18n ile üretilir (locales → errors.<KOD>).
 */
export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  CSRF_INVALID: 'CSRF_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SETUP_ALREADY_DONE: 'SETUP_ALREADY_DONE',
  SETUP_TOKEN_INVALID: 'SETUP_TOKEN_INVALID',

  ALREADY_MEMBER: 'ALREADY_MEMBER',
  INVITE_REQUIRES_LOGIN: 'INVITE_REQUIRES_LOGIN',
  INVITE_EMAIL_MISMATCH: 'INVITE_EMAIL_MISMATCH',
  LAST_OWNER: 'LAST_OWNER',
  OWNER_ONLY: 'OWNER_ONLY',

  WORK_ITEM_PARENT_REQUIRED: 'WORK_ITEM_PARENT_REQUIRED',
  WORK_ITEM_PARENT_NOT_ALLOWED: 'WORK_ITEM_PARENT_NOT_ALLOWED',
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
